Repository hidet-org/hidet, pull requests merged in 2023-01, with the labels that each got.

#68 [Docs] Add instructions for installing nightly version of hidet
  docs/source/getting-started/install.rst
Labels: documentation

#71 [Operator] Add dilation support for conv2d
  python/hidet/graph/frontend/onnx/onnx.py
  python/hidet/graph/frontend/torch/register_functions.py
  python/hidet/graph/ops/definitions/conv2d/conv2d.py
  python/hidet/graph/ops/definitions/conv2d/conv2d_gemm.py
  python/hidet/graph/ops/definitions/conv2d/resolve.py
  python/hidet/graph/ops/definitions/conv2d/utils.py
  tests/graph/operators/test_conv2d.py
  tests/graph/operators/test_conv2d_transpose.py
Labels: enhancement

#76 [Fixbug] Fix a bug in ``trace_from`` when the inputs are directly used as outputs
  python/hidet/graph/ir/flow_graph.py
  python/hidet/ir/dtypes/floats.py
Labels: bug

#75 [Operator] Add reduce_f16 and squeeze as Reduce's resolve variants
  python/hidet/graph/ops/definitions/__init__.py
  python/hidet/graph/ops/definitions/reduce/__init__.py
  python/hidet/graph/ops/definitions/reduce/reduce.py
  python/hidet/graph/ops/definitions/reduce/reduce_f16.py
  python/hidet/graph/ops/definitions/reduce/resolve.py
  tests/graph/operators/test_conv2d.py
  tests/graph/operators/test_reduce.py
Labels: enhancement

#79 [Operator] Add conv3d, max_pool3d, avg_pool3d
  python/hidet/graph/frontend/onnx/onnx.py
  python/hidet/graph/frontend/torch/register_functions.py
  python/hidet/graph/frontend/torch/register_modules.py
  python/hidet/graph/ops/__init__.py
  python/hidet/graph/ops/definitions/conv3d/__init__.py
  python/hidet/graph/ops/definitions/conv3d/conv3d.py
  python/hidet/graph/ops/definitions/conv3d/conv3d_gemm.py
  python/hidet/graph/ops/definitions/conv3d/resolve.py
  python/hidet/graph/ops/definitions/conv3d/utils.py
  python/hidet/graph/ops/definitions/pool.py
  tests/graph/operators/test_conv2d.py
  tests/graph/operators/test_conv3d.py
  tests/graph/operators/test_pool.py
Labels: enhancement
